# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UnitTesting
  jobs:
  - job: RunTests
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          python -V
          python -m pip install --upgrade pip setuptools wheel
          pip install -r video_rss/requirements.txt
          pip install -r tests/requirements.txt
          python -m pytest tests --junitxml=junit/test-results.xml --cov=main --cov-report=xml --cov-report=html
        displayName: 'Run Tests'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '$(System.DefaultWorkingDirectory)/**/test-*.xml'
          testRunTitle: 'Publish test results for Python 3.8'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura 
          summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
- stage: Deploy
  dependsOn: UnitTesting
  jobs:
  - job: DockerLinux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: $(dockerRegistry)
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: trixter1394/VideoRSS
        tags: latest
        dockerfile: ./Dockerfile
    - task: Docker@2
      inputs:
        command: logout