# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UnitTesting
  jobs:
  - job: InstallRequirementsAndRunTests
    steps:
      - script: pip install -r main/requirements.txt
        displayName: 'Install Script Requirements'
      - script: pip install -r test/requirements.txt
        displayName: 'Install Testing Requirements'
      - script: pytest test --html=report.html 
        displayName: 'Run Tests'
- stage: Deploy
  dependsOn: UnitTesting
  jobs:
  - job: DockerLinux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: $(dockerRegistry)
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: trixter1394/VideoRSS
        tags: latest
        dockerfile: ./Dockerfile
    - task: Docker@2
      inputs:
        command: logout
  - job: DockerWindows
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: $(dockerRegistry)
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: trixter1394/VideoRSS
        tags: windows-latest
        dockerfile: ./Dockerfile
    - task: Docker@2
      inputs:
        command: logout
